# -*- coding: utf-8 -*-
"""BART_Summarizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13aaGdcuTUR2V7khBmRKOclW2DRU8rPtb
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("summarization", model="facebook/bart-large-cnn")

!huggingface-cli login

from transformers import pipeline
import ipywidgets as widgets
from IPython.display import display

summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# Define the summarization function
def summarize_article(text):
    summary = summarizer(text, max_length=100, min_length=30, do_sample=False)
    return summary[0]['summary_text']

# Create UI elements
text_box = widgets.Textarea(
    description='Article:',
    placeholder='Enter your article here...',
    layout=widgets.Layout(width='100%', height='200px')
)
button = widgets.Button(description="Summarize")
output = widgets.Output()

# Define button click event
def on_button_click(b):
    with output:
        output.clear_output()
        if text_box.value:
            summary = summarize_article(text_box.value)
            print("Summary:", summary)
        else:
            print("Please enter some text to summarize.")

button.on_click(on_button_click)

# Display the UI
display(text_box, button, output)